# Generated by Django 3.2.3 on 2021-06-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingModel',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_number', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelClassModel',
            fields=[
                ('hotel_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hotel_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelclassmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsChainModel',
            fields=[
                ('hotels_chain_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomClassModel',
            fields=[
                ('room_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClassModel',
            fields=[
                ('service_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('street_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('execution_date', models.DateTimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.employeemodel')),
                ('service_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.serviceclassmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelmodel')),
                ('room_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.roomclassmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('mark', models.FloatField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='hotels_chain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelschainmodel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='function_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.functionmodel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelmodel'),
        ),
        migrations.CreateModel(
            name='BookingRequestModel',
            fields=[
                ('booking_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('planned_check_in_date', models.DateField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.hotelmodel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.roommodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.usermodel')),
            ],
        ),
    ]
