# Generated by Django 3.2.3 on 2021-06-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='buildings',
            field=models.ManyToManyField(to='database_view.BuildingModel'),
        ),
    ]
