# Generated by Django 3.2.3 on 2021-06-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0002_hotelmodel_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='street_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database_view.streetmodel'),
            preserve_default=False,
        ),
    ]
