# Generated by Django 3.2.3 on 2021-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0004_auto_20210602_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
