# Generated by Django 3.2.3 on 2021-06-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0005_roommodel_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequestmodel',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='bookingrequestmodel',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database_view.roommodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequestmodel',
            name='status',
            field=models.CharField(default='В обработке', max_length=20),
        ),
    ]
