# Generated by Django 3.2.3 on 2021-06-02 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0006_auto_20210602_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequestmodel',
            name='planned_check_out_date',
            field=models.DateField(default=datetime.date(2021, 6, 2)),
        ),
    ]
