# Generated by Django 3.2.3 on 2021-06-03 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0007_bookingrequestmodel_planned_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequestmodel',
            name='planned_check_out_date',
            field=models.DateField(default=datetime.date(2021, 6, 3)),
        ),
    ]
